# CREATE TABLES

staging_eia_table_create= ("""
create table if not exists staging_eia
(plant_id integer
,combined_heat_and_power_plant varchar
,nuclear_unit_id varchar
,plant_name varchar
,operator_name varchar
,operator_id decimal
,plant_state varchar
,census_region varchar
,nerc_region varchar
,reserved varchar
,naics_code varchar
,eia_sector_number integer
,sector_name varchar
,reported_prime_mover varchar
,reported_fuel_type_code varchar
,aer_fuel_type_code varchar
,balancing_authority_code varchar
,respondent_frequency varchar
,physical_unit_label varchar
,year integer
,month varchar
,elec_fuel_consumption_mmbtu decimal
,total_fuel_consumption_mmbtu decimal
,total_fuel_consumption_quantity decimal
,electric_fuel_consumption_quantity decimal
,net_generation_megawatthours decimal
,quantity decimal
,elec_quantity decimal
,mmbtu_per_unit decimal
,tot_mmbtu decimal
,elec_mmbtu decimal
,netgen decimal
,month_number integer
)
""")

staging_temperature_table_create= ("""
create table if not exists staging_temperature
(dt date
,AverageTemperature decimal
,AverageTemperatureUncertainty decimal
,State varchar
,Country varchar
)
""")

staging_demographics_table_create= ("""
create table if not exists staging_demographics
(City varchar
,State varchar
,Median_Age decimal
,Male_Population decimal
,Female_Population decimal
,Total_Population decimal
,Number_of_Veterans decimal
,Foreign_born decimal
,Average_Household_Size decimal
,State_Code varchar
,Race varchar
,Count decimal
)
""")

date_table_create = ("""
create table if not exists dim_date
(date_key integer primary key
,date date
,year integer
,month integer
,day integer
,weekday integer
)
""")

location_table_create = ("""
create table if not exists dim_location
(location_key integer identity(1,1) primary key
,country_code varchar
,country_name varchar
,state_code varchar
,state_name varchar
)
""")

plant_table_create = ("""
create table if not exists dim_plant
(plant_key integer generated by default as identity(1,1) primary key
,plant_id varchar
,plant_name varchar
,operator_id varchar
,operator_name varchar 
)
""")

temperature_table_create = ("""
create table if not exists fact_temperature
(date_key integer primary key
,location_key integer
,average_temperature decimal
,average_temperature_uncertainty decimal
)
""")

demographics_table_create = ("""
create table if not exists fact_demographics
(location_key integer primary key
,race varchar
,median_age decimal
,male_population integer
,female_population integer
,total_population integer
,number_of_veterans integer
,foreign_born integer
,average_household_size decimal
,count integer
)
""")

electricity_table_create = ("""
create table if not exists fact_electricity
(date_key integer primary key
,location_key integer
,plant_key integer
,fuel_type_key integer
,balancing_authority_key integer
,region_key integer
,eia_sector_key integer
,reported_prime_mover_key integer
,combined_heat_and_power_plant varchar
,nuclear_unit_id varchar
,naics_code integer
,physical_unit_label varchar
,quantity decimal
,elec_quantity decimal
,mmbtu_per_unit decimal
,tot_mmbtu decimal
,elec_mmbtu decimal
,netgen decimal
)
""")

dim_aer_fuel_type_table_create = ("""
create table if not exists dim_aer_fuel_type
(aer_fuel_type_key integer identity(1,1) primary key
,aer_fuel_type_code varchar
,aer_fuel_type_desc varchar
)
""")

dim_balancing_authority_table_create = ("""
create table if not exists dim_balancing_authority
(balancing_authority_key integer identity(1,1) primary key
,balancing_authority_code varchar
,balancing_authority_desc varchar
)
""")

dim_census_region_table_create = ("""
create table if not exists dim_census_region
(census_region_key integer identity(1,1) primary key
,census_region_code varchar
,census_region_desc varchar
)
""")

dim_eia_sector_table_create = ("""
create table if not exists dim_eia_sector
(eia_sector_key integer identity(1,1) primary key
,eia_sector_code varchar
,eia_sector_desc varchar
)
""")

dim_nerc_region_table_create = ("""
create table if not exists dim_nerc_region
(nerc_region_key integer identity(1,1) primary key
,nerc_region_code varchar
,nerc_region_desc varchar
)
""")

dim_reported_fuel_type_table_create = ("""
create table if not exists dim_reported_fuel_type
(reported_fuel_type_key integer identity(1,1) primary key
,reported_fuel_type_code varchar
,reported_fuel_type_desc varchar
)
""")

dim_reported_prime_mover_table_create = ("""
create table if not exists dim_reported_prime_mover
(reported_prime_mover_key integer identity(1,1) primary key
,reported_prime_mover_code varchar
,reported_prime_mover_desc varchar
)
""")

dim_fuel_type_table_create = ("""
create table if not exists dim_fuel_type
(fuel_type_key integer identity(1,1) primary key
,aer_fuel_type_code varchar
,aer_fuel_type_desc varchar
,reported_fuel_type_code varchar
,reported_fuel_type_desc varchar
)
""")

dim_region_table_create = ("""
create table if not exists dim_region
(region_key integer identity(1,1) primary key
,census_region_code varchar
,census_region_desc varchar
,nerc_region_code varchar
,nerc_region_desc varchar
)
""")



# QUERY LISTS

create_table_queries = [staging_eia_table_create, staging_temperature_table_create, staging_demographics_table_create, date_table_create, location_table_create, plant_table_create, temperature_table_create, demographics_table_create, electricity_table_create, dim_aer_fuel_type_table_create, dim_balancing_authority_table_create, dim_census_region_table_create, dim_eia_sector_table_create, dim_nerc_region_table_create, dim_reported_fuel_type_table_create, dim_reported_prime_mover_table_create, dim_fuel_type_table_create, dim_region_table_create]

#REDUCED LIST TO AVOID LOADING STAGING TABLES
# create_table_queries = [date_table_create, location_table_create, plant_table_create, temperature_table_create, demographics_table_create, electricity_table_create, dim_aer_fuel_type_table_create, dim_balancing_authority_table_create, dim_census_region_table_create, dim_eia_sector_table_create, dim_nerc_region_table_create, dim_reported_fuel_type_table_create, dim_reported_prime_mover_table_create, dim_fuel_type_table_create, dim_region_table_create]